version: "3"

services:
  #mongodb services
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  leave:
    build: ./leave-microservice
    environment:
      PORT: 3001
      DB_HOST: mongo_db
      USER_HOST: user
      LEAVE_HOST: leave
    depends_on:
      - user
      - mongo_db

  user:
    build: ./user-microservice
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DB_HOST: mongo_db
      USER_HOST: user
      LEAVE_HOST: leave
    depends_on:
      - mongo_db
